version: '3.8'

services:
  laravel_app:
    container_name: aeia-app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/sh -c " pwd &&
                  php artisan key:generate &&
                  php artisan serve --host=0.0.0.0 --port=8000"
    volumes:
      - .:/public
      - /public/vendor
    ports:
      - 8000:8000
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5632:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
